global using ShiroBot.Adapter.Milky.Model.Common;
global using ShiroBot.Adapter.Milky.Model.File.Requests;
global using ShiroBot.Adapter.Milky.Model.File.Responses;
global using ShiroBot.Adapter.Milky.Model.Friend.Requests;
global using ShiroBot.Adapter.Milky.Model.Friend.Responses;
global using ShiroBot.Adapter.Milky.Model.Group.Requests;
global using ShiroBot.Adapter.Milky.Model.Group.Responses;
global using ShiroBot.Adapter.Milky.Model.Message.Requests;
global using ShiroBot.Adapter.Milky.Model.Message.Responses;
global using ShiroBot.Adapter.Milky.Model.System.Requests;
global using ShiroBot.Adapter.Milky.Model.System.Responses;
global using static ShiroBot.Adapter.Milky.Milky.MilkyJson;
